name: Build and Deploy
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies and build 🔧
        run: yarn build
        
      - name: Publish package on NPM 📦
        run: npm run deploy-library
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}