name: Build and Deploy
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install dependencies and build 🔧
        run: yarn install && yarn build
        
      - name: Publish package on NPM 📦
        run: npm run deploy-library
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}